### ISSUE TITLE
Ensure control plane is circular

### ISSUE THREAD

**Issue by elmarti** [elmarti/react-joystick-component#11]
At present it is possible to move the joystick in a square fashion, however it should be a uniform circular like its parent. This could probably be solved with a trigonometric function.

This changes the functionality, but shouldn't cause issues for current users so, a minor version bump.

**Comment by elmarti** [comment]
https://github.com/elmarti/react-joystick-component/blob/b5ed4a63391ef82e241ccebb96d8bc874fe2a3de/src/Joystick.tsx#L138
`_getWithinBounds` should calc : 
![image](https://user-images.githubusercontent.com/4789968/43834105-e437d994-9b04-11e8-813f-c31be9cfc63c.png)

**Comment by JohanJarvi** [comment]
Any progress on this or do you need someone else to jump on it? It is weird that it moves in a square like fashion, makes it feel a lot less natural than it could be.

**Comment by elmarti** [comment]
@JohanJarvi not recently, It would also be a major release as I it will require some reworking of the core logic, but happy to take PRs. I haven't touched this codebase for a while, but as my past self mentioned, the `_getWithinBounds` function needs to be improved so that it calculates the position of the joystick as a function of the angle rather than just the size of the joystick.

I can't make any promises but i've been meaning to blitz the issues on this project. PRs are welcome but I may have a go in the next few day.

**Comment by behoyh** [comment]
In practice you also need [this function](https://math.stackexchange.com/questions/730427/determine-the-closest-point-along-a-circles-x-1-y-1-radius-from-any-point?noredirect=1&lq=1) to find the nearest point on the circumference in cases where x or y falls outside of the circle.
