### ISSUE TITLE
Joystick react to mouse move

### ISSUE THREAD

**Issue by Guillaume-succubus** [elmarti/react-joystick-component#24]
Hey, thanks for this package ! I was wondering if you know any way to make this move with mouse move ?

I mean, here you have to click on joystick then holding your click you can move anywhere. 
I'd like to be abble to say follow my mouse all the time in this precise location ?

thanks !

**Comment by elmarti** [comment]
@Guillaume-succubus this feature is now available with the `followCursor` prop https://github.com/elmarti/react-joystick-component/compare/2.3.0...3.0.0

Sorry about the delay!
