### ISSUE TITLE
Using joystick in ReactDOM.createPortal() in new window causes mouse drag to be on parent and in the original spot where it was rendered.

### ISSUE THREAD

**Issue by behoyh** [elmarti/react-joystick-component#26]
Got an interesting issue for you. when using the joystick in [a new window](https://medium.com/hackernoon/using-a-react-16-portal-to-do-something-cool-2a2d627b0202), it seems that the mouse move event binds to the parent window, and does not move from where the child window rendered the component.

**Comment by behoyh** [comment]
I was able to fix this by replacing all references to `window` with `this._baseRef`

**Comment by elmarti** [comment]
@behoyh awesome! are you able to put it into a PR?

**Comment by behoyh** [comment]
Right now I'm trying to fix some placement issues, hopefully I'll be able to fix it soon.

**Comment by elmarti** [comment]
Had a bit of a look into this today - No luck. 

It seems that React portals use the same `window` ref as the main DOM. 

I'm going to attempt to fix this over the next few weeks, but it'll need a bit of research

**Comment by elmarti** [comment]
I believe this is fixed in the above commit, feel free to reopen if anyone finds this is not the case - added a storybook with demo

**Comment by behoyh** [comment]
Very cool - thank you!!

**Comment by elmarti** [comment]
@behoyh did it resolve the issue for you?

**Comment by behoyh** [comment]
I don't have access to the codebase at this time so I cant say for certain.
