### ISSUE TITLE
Limit movements to X or Y axis

### ISSUE THREAD

**Issue by dswhy** [elmarti/react-joystick-component#55]
**Is your feature request related to a problem? Please describe.**
Currently there is no way (that I know) to limit the movement only to one axis. I intend to use this - otherwise amazing and simple to use - component for navigation along a 1-axis path (forwards/backwards). However, it can be confusing for the user if they can move the joystick into an axis that has no effect whatsoever.

**Describe the solution you'd like**
A flag such as `axis` where I can specify the axis I want to limit, e.g.: `JoystickAxis = ['auto', 'x', 'y']`

**Describe alternatives you've considered**
Limiting `touch-action` in the div or the page, results in limiting factor elsewhere. 
Other alternative implementations:
- Make the joystick position into a controlled variable, so I could manually set an axis value to 0.
- Extend controlPlaneShape to include axis-limited planes such as `JoystickShape.AxisY` and `JoystickShape.AxisX`

**Additional context**
No additional context

Thank you in advance! Would like to resolve this quickly if possible :)

**Comment by elmarti** [comment]
Thank you for your kind words! I will have a look into this later today or tomorrow

**Comment by elmarti** [comment]
@dswhy we already have the `stickShape` prop, does it meet your requirements if we were to add a lever style here e.g:

![image](https://user-images.githubusercontent.com/4789968/227483955-51c60bbf-af85-4533-bc15-5e8e1761f610.png)

**Comment by dswhy** [comment]
Is that similar to my alternative `controlPlaneShape` suggestion? I would like to keep the aesthetics and functionality mostly the same, just limit the movement to one axis (X or Y). If your proposal meets this, it will work for me :)

**Comment by elmarti** [comment]
Ah gotcha, got it working, making a release now

**Comment by dswhy** [comment]
Thank you so much!! It looks like the release didn't pass through all the check ups though! 😅

**Comment by elmarti** [comment]
@dswhy my bad - release failed due to this downstream issue: https://github.com/cycjimmy/semantic-release-action/issues/155 Should be available now

**Comment by dswhy** [comment]
It works great! Thanks a lot!
