### ISSUE TITLE
Add this component failed, report  `button` must be a function (received `undefined`)

### ISSUE THREAD

**Issue by Water-bamboo** [elmarti/react-joystick-component#67]
**Describe the bug**
Invariant Violation: View config getter callback for component `button` must be a function (received `undefined`). Make sure to start component names with a capital letter.

**To Reproduce**
1. npx react-native init TempProject
2. yarn add react-joystick-component 
3. add joystick as README.MD descripted.
4. yarn react-native run-android --verbose
5. See error

**Expected behavior**
Show the Joystick view

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [android]
 - OS: [10]
 - Version [rn 0.72]

**Additional context**
No special code, just add the Joystick view as README descripted.

**Comment by elmarti** [comment]
Hi @Water-bamboo unfortunately this component doesn't support React Native (at present) as we're using raw HTML elements. It's on my radar, but I don't know when i'l find time soon to work on this: https://github.com/elmarti/react-joystick-component/issues/9#issuecomment-1551639227
